### PR TITLE
Device Code Migration to AzIdentity Track 2

### LINKED ISSUE #2361: Auto-login not persisting token when AZCOPY_AUTO_LOGIN_TYPE=DEVICE
### Which version of the AzCopy was used? 
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
export AZCOPY_AUTO_LOGIN_TYPE=DEVICE
export AZCOPY_TENANT_ID=_tenant id_
... multiple azcopy commands

### What problem was encountered?
Have to enter code into web browser for _every_ azcopy command encountered a script.  Not a usable solution when there many commands.

### How can we reproduce the problem in the simplest way?
Should be easy to reproduce.  It appears from the code that auto-login disables token persistence altogether.

### Have you found a mitigation/solution?
Don't use auto-login, use `azcopy login` instead, but it's getting removed in 10.22.

Azure CLI persists tokens in ~/.azure folder; could azcopy do the same?

### PR DESCRIPTION
**Pull request by gapra-msft**
Resolves #2361 

Note: We need to test with personal accounts right now.

### CODE REVIEW

File: e2etest/zt_newe2e_oauth_device_test.go [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+	// no local->local
+	if srcObj.Location().IsLocal() && dstObj.Location().IsLocal() {
+		svm.InvalidateScenario()
+		return
+	}
+
+	sasOpts := GenericAccountSignatureValues{}
+
+	stdout, _ := RunAzCopy(
```
Comment (adreed-msft) [inline e2etest/zt_newe2e_oauth_device_test.go:46]: Can we validate that stdout is noting that we're connecting via AAD?

**Review by adreed-msft — APPROVED** [review]

File: common/oauthTokenManager.go [hunk 2]
```diff
@@ -682,59 +641,48 @@ func (credInfo *OAuthTokenInfo) GetWorkloadIdentityCredential() (azcore.TokenCre
...
 
-	if err := spt.RefreshWithContext(ctx); err != nil {
-		return nil, err
+	if record == (azidentity.AuthenticationRecord{}) {
+		// No stored record; call Authenticate to acquire one
+		record, err = tc.Authenticate(context.TODO(), &policy.TokenRequestOptions{Scopes: []string{StorageScope}})
+		if err != nil {
+			return nil, err
+		}
+		if credInfo.Tenant == DefaultTenantID {
```
[the remark this answers is not in the document]
Comment (dphulkar-msft) [reply common/oauthTokenManager.go:678]: Could you please help me explain a scenario why this needs to be sync.Once? I can't see tenant as a shared resource in the login workflow. Please correct me if I am wrong.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 1 above)
Comment (dphulkar-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:46]: I am not sure if we can get this information from stdout for validating if we are connected via AAD. Will check.

File: common/oauthTokenManager.go [hunk 3]
```diff
@@ -42,6 +42,9 @@ import (
 	"github.com/Azure/go-autorest/autorest/date"
 
 	"github.com/Azure/go-autorest/autorest/adal"
```
Comment (vibhansa-msft) [inline common/oauthTokenManager.go:44]: We still have reference to adal.Token in the code which shall be removed as adal package itself is deprecated now and as part of our Track-2 migration we have moved to msal. Refresh() method in this file still relies on adal.Token so we might need wider changes to remove adal dependency completely here.

File: common/oauthTokenManager.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (adreed-msft) [reply common/oauthTokenManager.go:678]: On the off-chance we call GetDeviceCodeCredential multiple times for whatever reason, stdout might look like...

```
INFO: Logging in under the...
INFO: If you plan to use...
INFO: Logging in under the...
INFO: If you plan to use...
INFO: Logging in under the...
INFO: If you plan to use...
```

This is quite spammy. Granted, it would be a decent indicator a mistake has been made, though.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 1 above)
Comment (adreed-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:46]: We most definitely do log this information. Please check `credentialUtil.go`, it is logged by `logAuthType`. If it is not, and we are authorizing something, that is a bug.

File: common/oauthTokenManager.go (hunk 3 above)
Comment (gapra-msft) [reply common/oauthTokenManager.go:44]: Unfortunately we need to keep this to maintain compatibility with storage explorer. We can take up an item to work with them to change the format of the token they send but that may take another release cycle or 2. 

For now to remove the dep I should be able to manually copy the adal.Token type into our codebase, so I will do that.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 1 above)
Comment (gapra-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:51]: Done

File: e2etest/zt_newe2e_oauth_device_test.go [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+	"github.com/Azure/azure-storage-azcopy/v10/common"
+	"github.com/Azure/azure-storage-azcopy/v10/testSuite/cmd"
+	"path"
+	"strings"
+	"time"
+)
+
+var runDeviceCodeTest = flag.Bool("device-code", false, "Whether or not to run device code tests. These must be run manually due to interactive nature.")
+
+var manualEnv AzCopyEnvironment
```
Comment (adreed-msft) [inline e2etest/zt_newe2e_oauth_device_test.go:14]: Unused; code smell as documented in next comment

File: e2etest/zt_newe2e_oauth_device_test.go [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+
+func init() {
+	if runDeviceCodeTest != nil && *runDeviceCodeTest {
+		suiteManager.RegisterSuite(&DeviceLoginManualSuite{})
+	}
+}
+
+func Scenario_CopySync(svm *ScenarioVariationManager, env *AzCopyEnvironment) {
```
Comment (adreed-msft) [inline e2etest/zt_newe2e_oauth_device_test.go:22]: env also is unused and this has a code smell about it

If the goal were to set up a consistent environment for the suite, the best idea would be to add it as a field under the suite struct, but between a global function and a global variable, this feels like an odd implementation.

That said, neither of these wind up getting used, so, it should get removed.

File: e2etest/zt_newe2e_oauth_device_test.go [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+		})
+
+	ValidateResource[ObjectResourceManager](svm, dstObj, ResourceDefinitionObject{
+		Body: body,
+	}, true)
+
+	ValidateAADAuth(svm, stdout, srcObj.Location(), dstObj.Location())
+}
+
+func ValidateAADAuth(a Asserter, stdout AzCopyStdout, src, dst common.Location) {
```
Comment (adreed-msft) [inline e2etest/zt_newe2e_oauth_device_test.go:77]: These also have a code smell about them-- I wanted to say we have a way to validate that stdout contains certain lines already, but, this is probably fine.

File: e2etest/zt_newe2e_oauth_device_test.go [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+	}
+	a.AssertNow("login should be successful", Equal{}, loggedIn, true)
+}
+
+func (s *DeviceLoginManualSuite) TeardownSuite(a Asserter) {
+	RunAzCopyLoginLogout(a, AzCopyVerbLogout)
+}
+
+func (s *DeviceLoginManualSuite) Scenario_CopySync(svm *ScenarioVariationManager) {
+	Scenario_CopySync(svm, nil)
```
Comment (adreed-msft) [inline e2etest/zt_newe2e_oauth_device_test.go:117]: ditto, this is odd.

File: e2etest/newe2e_task_runazcopy_login_logout.go [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+	}
+
+	return
+}
+
+func (a *AzCopyInteractiveStdout) String() string {
+	return strings.Join(a.RawStdout(), "\n")
+}
+
+func RunAzCopyLoginLogout(a Asserter, verb AzCopyVerb) AzCopyStdout {
```
Comment (adreed-msft) [inline e2etest/newe2e_task_runazcopy_login_logout.go:45]: This is also interesting to me-- Is there a reason to prefer a separate function over integrating with RunAzCopy?

File: e2etest/newe2e_task_runazcopy.go [hunk 9]
```diff
@@ -337,8 +342,10 @@ func RunAzCopy(a ScenarioAsserter, commandSpec AzCopyCommand) (AzCopyStdout, *Az
 		0, command.ProcessState.ExitCode())
 
 	a.Cleanup(func(a ScenarioAsserter) {
-		UploadLogs(a, out, stderr, DerefOrZero(commandSpec.Environment.LogLocation))
-		_ = os.RemoveAll(DerefOrZero(commandSpec.Environment.LogLocation))
+		if !commandSpec.Environment.ManualLogin {
```
Comment (adreed-msft) [inline e2etest/newe2e_task_runazcopy.go:345]: This also interests me-- I suspect this is to prevent capturing the login token, but, could we not filter that out?

**Review by adreed-msft — APPROVED** [review]
Tests have some funk about them, but otherwise lgtm. If we don't do anything about it now, I'll go in and do some housekeeping on the testing framework when I get time in December.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 4 above)
Comment (gapra-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:14]: this is accidental leftover from some of my debugging. will remove.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 5 above)
Comment (gapra-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:22]: this is accidental leftover from some of my debugging. will remove.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 7 above)
Comment (gapra-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:117]: I did this so that we can eventually have more suites for the other OAuth methods, then we can just reference the one test and call it like this. But this might be overthinking/overplanning things

File: e2etest/newe2e_task_runazcopy_login_logout.go (hunk 8 above)
Comment (gapra-msft) [reply e2etest/newe2e_task_runazcopy_login_logout.go:45]: I did this mostly because login needs some interactive stdout, whereas RunAzCopy is just reading the stdout. There is probably a clean way to integrate it with the other method. this can be cleaned this up after the PR is merged

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 6 above)
Comment (gapra-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:77]: Forgot about that, will fix to use that instead.

File: e2etest/newe2e_task_runazcopy.go (hunk 9 above)
Comment (gapra-msft) [reply e2etest/newe2e_task_runazcopy.go:345]: Currently the new e2e test framework is designed such that each of the scenarios creates a new temp log location. When you log in it creates a file in the log location and we want that log in to be the same across all e2e test framework logs, so we avoid removing the log folder. There is probably  a cleaner way to do this that we can look into during a cleanup PR.

File: e2etest/zt_newe2e_oauth_device_test.go (hunk 7 above)
Comment (gapra-msft) [reply e2etest/zt_newe2e_oauth_device_test.go:117]: This can easily be refactored during the cleanup PR, so I will leave this for now.

**Review by vibhansa-msft — APPROVED** [review]
